#!/usr/bin/env php
<?php

date_default_timezone_set('Asia/Shanghai'); //set timezone

require __DIR__ . '/vendor/autoload.php';

require __DIR__ . '/app/helpers.php';

$appConfig = config('app');

if ( ! $appConfig->active ) {
    exit();
}

$app = new \App\Application(new $appConfig->data_provider, new $appConfig->notification);

$app->run();